---
title: "p8105_hw5_ak4123"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(purrr)

set.seed(1)

```

#Question 1
This zip file contains data from a longitudinal study that included a control arm and an experimental arm. Data for each participant is included in a separate file, and file names include the subject ID and arm.
Create a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time:
```{r question 1}

files = list.files("./data", full.names = TRUE)
data_files = 
  tibble(
  treatment =  str_detect(files, "con"),
  participant_id = str_extract(files, "\\d+(?=.csv)"),
  data = map(.x = files, ~read.csv(.x))
  )
data_files =
  data_files %>% 
  unnest %>% 
  mutate(treatment = case_when(treatment == TRUE ~ "Control",
                         treatment == FALSE ~ "Experimental")
  ) %>% 
  gather(key = "week", week_1:week_8, value = "value") %>% 
  mutate(week = as.numeric(str_extract(week, "\\d"))) %>% 
  arrange(treatment, participant_id)
data_files

ggplot(data_files, aes(x = week, y = value, color = participant_id)) + 
  facet_grid(.~treatment) + 
  geom_line() + 
 viridis::scale_color_viridis(
      discrete = TRUE,
      name = "participant id"
    ) +
    labs(
      x = "week",
      y = "value",
      title = "Observed Values by Treatment Group over Time"
    ) +
    theme_bw()

```
